# services:
#   app:
#     build:
#       context: .
#     ports:
#       - '3000:3000'
#     volumes:
#       - .:/src
#       - node_modules:/src/node_modules
#     environment:
#       NODE_ENV: development
#
# volumes:
#   node_modules: {}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    environment:
      NODE_ENV: development

  code:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    ports:
      - "8443:8443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
      - PASSWORD=devpass   # change this!
    volumes:
      - .:/src
      - node_modules:/src/node_modules
      - code_config:/config

volumes:
  node_modules: {}
  code_config: {}
